/// <reference path="./.sst/platform/config.d.ts" />

/**
 * SST app definition (P0-11).
 *
 * Note the version: the plan says "SST v3", but that line has moved — v4 is
 * the current release of the same Pulumi-based lineage, so this pins v4.17.1.
 *
 * `$config`, `$app` and the `sst.aws.*` namespace are globals injected by SST
 * and typed by `.sst/platform/config.d.ts`, which is generated by `sst install`
 * and is gitignored. That is why this file is outside every tsconfig and is not
 * covered by `pnpm typecheck` — see the open items in Part 11.
 */

/**
 * One region, named once.
 *
 * `eu-west-1` (Ireland), confirmed as a decision rather than inherited as a
 * default. It satisfies the three constraints that bind here simultaneously:
 * EU data residency for sellers' customer data, availability of the Bedrock
 * models §5.3 depends on, and cost — eu-south-1 (Milan) is nearer to users but
 * pricier with thinner service coverage.
 *
 * Region availability is necessary but not sufficient for Bedrock: each model
 * must also be granted in the account before it can be invoked.
 */
const AWS_REGION = 'eu-west-1';

/**
 * Stages that get production-grade protection.
 *
 * Both spellings on purpose. The guard is an exact string match, so a stage
 * deployed as `production` instead of `prod` would silently be treated as
 * ephemeral and be removable — a naming slip should not be what decides
 * whether the production database can be deleted.
 */
const PROTECTED_STAGES = new Set(['prod', 'production']);

export default $config({
  app(input) {
    const stage = input?.stage ?? 'dev';
    const isProtected = PROTECTED_STAGES.has(stage);

    return {
      name: 'sommelier',
      home: 'aws',

      // `retain` keeps resources when the stage is removed; `protect` refuses
      // `sst remove` on the stage outright. Both, because they fail
      // differently: retain survives an intentional removal, protect stops the
      // accident. The production database is the thing being defended.
      removal: isProtected ? 'retain' : 'remove',
      protect: isProtected,

      providers: {
        // Supplies `random.RandomPassword` for the database role credentials
        // (P0-21a). Declared here because SST injects a provider's global only
        // for the providers an app names; `sst install` regenerates the
        // typings that make `random` visible to `pnpm typecheck:infra`.
        random: '4.16.6',

        aws: {
          region: AWS_REGION,
          // Cost-allocation tags cannot be retrofitted usefully: spend that
          // was untagged when it happened stays unattributable forever (§5.8).
          // `defaultTags` applies these to every taggable resource, so a new
          // component cannot forget them.
          defaultTags: {
            tags: {
              env: stage,
              service: 'sommelier',
            },
          },
        },
      },
    };
  },

  async run() {
    // Dynamic import, which is how SST expects infra to be pulled in: the
    // module body runs inside the app context, where the `sst.*` globals exist.
    await import('./infra/vpc');
    await import('./infra/database');
    await import('./infra/config');
    await import('./infra/budgets');
    await import('./infra/cdn');
    await import('./infra/api');
  },
});
