/// <reference path="./.sst/platform/config.d.ts" />

/**
 * SST app definition (P0-11).
 *
 * Note the version: the plan says "SST v3", but that line has moved — v4 is
 * the current release of the same Pulumi-based lineage, so this pins v4.17.1.
 *
 * `$config`, `$app` and the `sst.aws.*` namespace are globals injected by SST
 * and typed by `.sst/platform/config.d.ts`, which is generated by `sst install`
 * and is gitignored. That is why this file is outside every tsconfig and is not
 * covered by `pnpm typecheck` — see the open items in Part 11.
 */

/**
 * One region, named once.
 *
 * ASSUMPTION, NOT A DECISION FROM THE PLAN — §5 never pins a region. It has to
 * satisfy three constraints at once, so it is worth confirming before the first
 * deploy rather than after:
 *   1. EU data residency (the product is Italian-market, sellers' customer data).
 *   2. Availability of the chosen Bedrock model (§5.3 defaults to Nova Lite).
 *      Bedrock model coverage varies by region and is the binding constraint.
 *   3. Cost. eu-south-1 (Milan) is closer to users but pricier and has thinner
 *      service coverage than eu-west-1.
 * eu-west-1 is the conservative pick. Changing it before anything is deployed
 * costs one line; changing it afterwards is a migration.
 */
const AWS_REGION = 'eu-west-1';

/**
 * Stages that get production-grade protection.
 *
 * Both spellings on purpose. The guard is an exact string match, so a stage
 * deployed as `production` instead of `prod` would silently be treated as
 * ephemeral and be removable — a naming slip should not be what decides
 * whether the production database can be deleted.
 */
const PROTECTED_STAGES = new Set(['prod', 'production']);

export default $config({
  app(input) {
    const stage = input?.stage ?? 'dev';
    const isProtected = PROTECTED_STAGES.has(stage);

    return {
      name: 'sommelier',
      home: 'aws',

      // `retain` keeps resources when the stage is removed; `protect` refuses
      // `sst remove` on the stage outright. Both, because they fail
      // differently: retain survives an intentional removal, protect stops the
      // accident. The production database is the thing being defended.
      removal: isProtected ? 'retain' : 'remove',
      protect: isProtected,

      providers: {
        aws: {
          region: AWS_REGION,
          // Cost-allocation tags cannot be retrofitted usefully: spend that
          // was untagged when it happened stays unattributable forever (§5.8).
          // `defaultTags` applies these to every taggable resource, so a new
          // component cannot forget them.
          defaultTags: {
            tags: {
              env: stage,
              service: 'sommelier',
            },
          },
        },
      },
    };
  },

  async run() {
    // Dynamic import, which is how SST expects infra to be pulled in: the
    // module body runs inside the app context, where the `sst.*` globals exist.
    await import('./infra/vpc');
    await import('./infra/database');
    await import('./infra/config');
  },
});
