-- Reverses the row-level security migration (P0-37).

DROP POLICY IF EXISTS tenant_isolation ON tenants;
ALTER TABLE tenants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON memberships;
ALTER TABLE memberships NO FORCE ROW LEVEL SECURITY;
ALTER TABLE memberships DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON tenant_domains;
ALTER TABLE tenant_domains NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_domains DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON widget_keys;
ALTER TABLE widget_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE widget_keys DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON products;
ALTER TABLE products NO FORCE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON product_embeddings;
ALTER TABLE product_embeddings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE product_embeddings DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON conversations;
ALTER TABLE conversations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON messages;
ALTER TABLE messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON widget_events;
ALTER TABLE widget_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE widget_events DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON usage_events;
ALTER TABLE usage_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE usage_events DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON usage_daily;
ALTER TABLE usage_daily NO FORCE ROW LEVEL SECURITY;
ALTER TABLE usage_daily DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON audit_log;
ALTER TABLE audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON security_events;
ALTER TABLE security_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE security_events DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON token_revocations;
ALTER TABLE token_revocations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE token_revocations DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON outbox;
ALTER TABLE outbox NO FORCE ROW LEVEL SECURITY;
ALTER TABLE outbox DISABLE ROW LEVEL SECURITY;
