-- Row-level security for invitations (P0-51).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- Acceptance reads this table before the caller is a member of the tenant, which is what accepting means, so the boilerplate returns zero rows on the one path that must work.
-- The token branch is safe where a tenant branch would not be because the value is a 256-bit secret rather than an identifier: holding it is the authorization.
-- WITH CHECK stays tenant-only, so nobody can insert an invitation into a tenant they are not in.
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON invitations
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR token_hash = nullif(current_setting('app.invitation_token', true), ''))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
