-- The outbox poller reads across tenants (P1-31).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- The poller drains every tenant’s queue in one pass, so there is no tenant to scope it to and the boilerplate returns zero rows — silently, which is the failure this would actually have had.
-- Unlike the user and invitation branches above, this one does not narrow to the caller’s own rows; it is an unlock, and it is confined to this table because a policy cannot reach further.
-- An outbox row carries ids, an event name and a one-word reason, never catalogue content, and the worker re-enters withTenant before it reads a product.
CREATE POLICY outbox_poller_read ON outbox
  FOR SELECT
  USING (nullif(current_setting('app.outbox_poller', true), '') = 'on');
--> statement-breakpoint
-- Publishing a job ends in an UPDATE — processed_at, or the attempt counter — so a read-only unlock would leave the poller able to claim work it could never release.
-- Split from the read rather than written as one FOR ALL policy, so the flag admits exactly the two commands the queue needs: no INSERT, so no path can forge a job for another tenant, and no DELETE, so none can drop one.
CREATE POLICY outbox_poller_release ON outbox
  FOR UPDATE
  USING (nullif(current_setting('app.outbox_poller', true), '') = 'on')
  WITH CHECK (nullif(current_setting('app.outbox_poller', true), '') = 'on');
