-- The outbox poller reads across tenants (P1-31).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- The poller drains every tenant’s queue in one pass, so there is no tenant to scope it to and the boilerplate returns zero rows — silently, which is the failure this would actually have had.
-- Unlike the user and invitation branches above, this branch does not narrow to the caller’s own rows: it is a read across every tenant, of a table whose rows carry ids, an event name and a one-word reason rather than anything a seller wrote.
-- WITH CHECK stays tenant-only, exactly as memberships does, and here it does more work: the poller’s release is an UPDATE, so it has to set app.tenant_id from the row it claimed before it writes.
-- The flag therefore buys a read and nothing else — no insert of a job naming another tenant, and no delete of one.
DROP POLICY IF EXISTS tenant_isolation ON outbox;
CREATE POLICY tenant_isolation ON outbox
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR nullif(current_setting('app.outbox_poller', true), '') = 'on')
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
