-- The widget resolves its tenant from a key and an origin (P2-07).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- The widget has to learn its tenant from the public key before any tenant is known, so the boilerplate returns zero rows on the one path that must work (P2-07, ADR 0022).
-- The key branch admits exactly the presented key’s row, the key being unique.
-- WITH CHECK stays tenant-only, and withWidgetKey opens its transaction READ ONLY, so the branch buys a read of one row and nothing else.
DROP POLICY IF EXISTS tenant_isolation ON widget_keys;
CREATE POLICY tenant_isolation ON widget_keys
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR public_key = nullif(current_setting('app.widget_key', true), ''))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
--> statement-breakpoint
-- The same resolution needs the domain the request came from.
-- The origin alone is not enough: the branch admits the domain only when it belongs to the presented key’s own tenant, so an origin verified by one winery is invisible to a key issued to another.
-- WITH CHECK stays tenant-only, and the widget scope cannot write.
DROP POLICY IF EXISTS tenant_isolation ON tenant_domains;
CREATE POLICY tenant_isolation ON tenant_domains
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (origin = nullif(current_setting('app.widget_origin', true), '')
      AND tenant_id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), ''))))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
--> statement-breakpoint
-- The widget needs the tenant’s status, plan and locale once the pair agrees.
-- The row is reachable only behind a VERIFIED domain whose tenant owns the presented key, so a key on its own, or a pending claim, never reaches a tenant row.
-- WITH CHECK stays tenant-only, and the widget scope cannot write.
DROP POLICY IF EXISTS tenant_isolation ON tenants;
CREATE POLICY tenant_isolation ON tenants
  USING (id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR id IN (SELECT d.tenant_id FROM tenant_domains d
      WHERE d.origin = nullif(current_setting('app.widget_origin', true), '') AND d.status = 'VERIFIED'
        AND d.tenant_id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), ''))))
  WITH CHECK (id = nullif(current_setting('app.tenant_id', true), '')::uuid);
