-- The sweep deletes lapsed token revocations across tenants (P2-14).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- The sweep deletes lapsed revocations for every tenant in one statement, so the boilerplate returns zero rows, silently, on the one path that has to reach all of them (P2-14, ADR 0023).
-- The flag never admits a row on its own: only a revocation whose token lapsed more than the continuation window ago, so one that could still refuse a continuing session is invisible to it.
-- WITH CHECK stays tenant-only, so the flag can neither write a revocation nor move one.
DROP POLICY IF EXISTS tenant_isolation ON token_revocations;
CREATE POLICY tenant_isolation ON token_revocations
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (nullif(current_setting('app.revocation_sweeper', true), '') = 'on'
      AND expires_at < now() - make_interval(secs => 1800)))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
