-- Row-level security for session cutoffs (P4-06).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- Nothing but the boilerplate, and that is the whole point of where it is read (P4-06).
-- A cutoff is consulted on the widget request path — but only after CORS has resolved the tenant from (pk_, Origin), so it is read inside an ordinary withTenant, exactly as isTokenRevoked reads token_revocations two checks earlier on the same request.
-- No new GUC, no seventh context: the one thing a new table here could have cost, and did not.
ALTER TABLE widget_session_cutoffs ENABLE ROW LEVEL SECURITY;
ALTER TABLE widget_session_cutoffs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON widget_session_cutoffs
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
