-- A server finds its tenant from a secret key (P4-10).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- A server presenting a secret key has no tenant yet, so the boilerplate returns zero rows on the one path that must find one (P4-10, ADR 0026).
-- The branch admits exactly the active row whose hash is the one presented — and revoked_at IS NULL is load-bearing, because a public key rotation carries the hash onto the new row and the revoked one keeps its copy through the grace window (P4-08). resolveTenantBySecretKey clears the GUC as soon as it has read the row and continues as an ordinary tenant scope, READ ONLY.
-- WITH CHECK stays tenant-only.
DROP POLICY IF EXISTS tenant_isolation ON widget_keys;
CREATE POLICY tenant_isolation ON widget_keys
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR public_key = nullif(current_setting('app.widget_key', true), '')
    OR (secret_key_hash = nullif(current_setting('app.secret_key_hash', true), '') AND revoked_at IS NULL))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
