-- A proven claim reaches the domain it names (P4-18).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- Two tenants on one row (P4-18, ADR 0028).
-- The claimant owns it, as tenant_id.
-- The holder a proven claim has put on notice must see it too, or the notice could not be answered — so incumbent_tenant_id admits it once it is set, and it is set only with a notice.
-- The holder writes exactly one thing, a withdrawal, so its half of WITH CHECK admits only a CANCELED row: a holder cannot write a live claim, least of all one naming somebody else as claimant.
ALTER TABLE domain_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE domain_claims FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON domain_claims
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR incumbent_tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (incumbent_tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND status = 'CANCELED'));
--> statement-breakpoint
-- Settling a claim has to find the holder of an origin, and RLS hides every other winery’s rows — which is correct everywhere else, and the reason P4-01 can only say "not available" (P4-18, ADR 0028).
-- The branch admits the one domain whose origin a settleable claim names: a claim the current tenant can see, that has been proved by DNS, or whose notice has run out.
-- A claim awaiting proof, a notice with time left and a withdrawn claim admit nothing. settleDomainClaim clears the GUC as soon as it has read the holder and continues under the holder’s ordinary tenant scope.
-- WITH CHECK stays tenant-only.
DROP POLICY IF EXISTS tenant_isolation ON tenant_domains;
CREATE POLICY tenant_isolation ON tenant_domains
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (origin = nullif(current_setting('app.widget_origin', true), '')
      AND tenant_id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), '')))
    OR origin IN (SELECT c.origin FROM domain_claims c
      WHERE c.id = nullif(current_setting('app.domain_claim', true), '')::uuid
        AND (c.status = 'PROVEN'
          OR (c.status = 'NOTICE' AND c.transfer_at <= now()))))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
