-- The claim sweep finds its work, and a notice counts once sent (P4-18b).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- The claim sweep sends each notice, settles each notice that has run out, and tells both wineries how a claim ended — and learning which claims need any of that is itself the cross-tenant read (P4-18b, ADR 0028).
-- The flag never admits a row on its own: only a claim on notice, or a settled or withdrawn one whose outcome has not been notified.
-- A claim awaiting proof, and every claim already told, stay invisible to it.
-- WITH CHECK is unchanged, so the flag buys a read; the sweep writes as the claimant or the holder.
DROP POLICY IF EXISTS tenant_isolation ON domain_claims;
CREATE POLICY tenant_isolation ON domain_claims
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR incumbent_tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (nullif(current_setting('app.claim_sweeper', true), '') = 'on'
      AND (status = 'NOTICE'
        OR (status IN ('TRANSFERRED', 'CANCELED') AND notified_status IS DISTINCT FROM status))))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (incumbent_tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid AND status = 'CANCELED'));
--> statement-breakpoint
-- A notice now counts only once it has been sent (P4-18b).
-- The branch still admits the domain a proven claim names, but a claim on notice reaches it only with notified_at set and transfer_at passed — so a holder nobody told cannot lose its origin, whatever the code settling it believes.
DROP POLICY IF EXISTS tenant_isolation ON tenant_domains;
CREATE POLICY tenant_isolation ON tenant_domains
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR (origin = nullif(current_setting('app.widget_origin', true), '')
      AND tenant_id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), '')))
    OR origin IN (SELECT c.origin FROM domain_claims c
      WHERE c.id = nullif(current_setting('app.domain_claim', true), '')::uuid
        AND (c.status = 'PROVEN'
          OR (c.status = 'NOTICE' AND c.notified_at IS NOT NULL AND c.transfer_at <= now()))))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
