-- A winery in development mode is reachable from its one local origin (P4-19b).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- Development mode (P4-19b): a seller’s developer serves the widget from one exact local origin for twenty-four hours.
-- The branch admits the winery only for its own key, only from that exact origin, and only while dev_mode_expires_at is in the future — so the expiry is the database’s, and the grant ends on time whatever the code believes.
-- WITH CHECK stays tenant-only, and the widget scope cannot write.
DROP POLICY IF EXISTS tenant_isolation ON tenants;
CREATE POLICY tenant_isolation ON tenants
  USING (id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR id IN (SELECT d.tenant_id FROM tenant_domains d
      WHERE d.origin = nullif(current_setting('app.widget_origin', true), '') AND d.status = 'VERIFIED'
        AND d.tenant_id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), '')))
    OR (dev_origin = nullif(current_setting('app.widget_origin', true), '')
      AND dev_mode_expires_at > now()
      AND id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), ''))))
  WITH CHECK (id = nullif(current_setting('app.tenant_id', true), '')::uuid);
