-- Row-level security for message top-ups (P5-11a).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

ALTER TABLE usage_top_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_top_ups FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON usage_top_ups
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
