-- Row-level security for charges awaiting an e-invoice (P5-03a).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

ALTER TABLE e_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE e_invoices FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON e_invoices
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
