-- The nightly rollup lists every tenant, read only (P5-13).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- The nightly rollup (P5-13) writes a row for every tenant, each day, including days with nothing in them — so it has to know every tenant, and learning that is itself the read across tenants (ADR 0030).
-- The branch admits every row, and what bounds it is where it is set: only listTenantDirectory sets it, inside a READ ONLY transaction, for one statement that selects the id and the creation time.
-- WITH CHECK stays tenant-only, so even a writable transaction holding the flag could not move a row.
DROP POLICY IF EXISTS tenant_isolation ON tenants;
CREATE POLICY tenant_isolation ON tenants
  USING (id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR id IN (SELECT d.tenant_id FROM tenant_domains d
      WHERE d.origin = nullif(current_setting('app.widget_origin', true), '') AND d.status = 'VERIFIED'
        AND d.tenant_id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), '')))
    OR (dev_origin = nullif(current_setting('app.widget_origin', true), '')
      AND dev_mode_expires_at > now()
      AND id IN (SELECT k.tenant_id FROM widget_keys k WHERE k.public_key = nullif(current_setting('app.widget_key', true), '')))
    OR nullif(current_setting('app.tenant_directory', true), '') = 'on')
  WITH CHECK (id = nullif(current_setting('app.tenant_id', true), '')::uuid);
