-- A Shopify webhook finds its winery by shop, read only (P6-06).
--
-- Generated by `rlsMigrationSql()` in src/rls.ts. Do not edit by hand:
-- `test/rls.test.ts` regenerates this file and fails if the two disagree,
-- which is what stops a table being added to the list and not to the database.

-- A Shopify webhook names its shop and nothing else (P6-06, ADR 0031), so the winery that holds the shop is learned from this table before any tenant is known.
-- The branch admits the one row for the shop the flag names, on this table only, and only resolveTenantByShop sets it, inside a READ ONLY transaction, before handing over to withTenant.
-- WITH CHECK stays tenant-only.
ALTER TABLE shopify_installations ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopify_installations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON shopify_installations
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR shop = nullif(current_setting('app.shopify_shop', true), ''))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
--> statement-breakpoint
-- The install callback is a redirect from Shopify and carries no tenant, so it finds the state in the scope of the member who started the install — the memberships argument, on one more table.
-- It spends the state by deleting it, which only USING governs; WITH CHECK stays tenant-only, so the user scope cannot write a state naming any winery.
ALTER TABLE shopify_oauth_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopify_oauth_states FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON shopify_oauth_states
  USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid
    OR user_id = nullif(current_setting('app.user_id', true), ''))
  WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
